name: NShop Common Application

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - src/NShop.Common/NShop.Common.Application/**
      - src/NShop.Common/Tests/NShop.Common.Application.Tests/**

env:
  PROJECT_PATH: src/NShop.Common/NShop.Common.Application/NShop.Common.Application.csproj
  TEST_PROJECT_PATH: src/NShop.Common/Tests/NShop.Common.Application.Tests/NShop.Common.Application.Tests.csproj

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore ${{ env.PROJECT_PATH }}
    - name: Build
      run: dotnet build --no-restore ${{ env.PROJECT_PATH }}
    - name: Test
      run: dotnet test ${{ env.TEST_PROJECT_PATH }}
